const express = require('express');
const router = express.Router();
const Quiz = require('../models/Quiz');
const quizController = require('../controllers/quizController');

// Route pour récupérer tous les quiz
router.get('/api/quizzes', quizController.index);

// Route pour récupérer un quiz par son ID
router.get('/api/quizzes/:id', quizController.show);

// Route pour créer un nouveau quiz
// Exemple de structure :
// {
//   "title": "Quiz Histoire de France",
//   "description": "Questions sur l'histoire de France",
//   "category": "Histoire",
//   "createdBy": "Admin",
//   "isAutoGenerated": false
// }
router.post('/api/quizzes', quizController.create);

// Route pour modifier un quiz
router.put('/api/quizzes/:id', quizController.update);

// Route pour supprimer un quiz (et toutes ses questions)
router.delete('/api/quizzes/:id', quizController.delete);

// Route pour dupliquer un quiz
router.post('/api/quizzes/:id/duplicate', quizController.duplicate);

module.exports = router;
