const mongoose = require('mongoose');

// Définition du schéma pour les quiz
const QuizSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: false },
  category: { type: String, required: true },
  createdBy: { type: String, required: true }, 
  isAutoGenerated: { type: Boolean, default: false },
  questionsCount: { type: Number, default: 0 } 
}, {
  timestamps: true 
});

const Quiz = mongoose.model('Quiz', QuizSchema);

module.exports = Quiz;
